name: Update Playoff Leaderboard

on:
  workflow_dispatch: # Позволяет запускать вручную кнопку
  schedule:
    - cron: '0 */3 * * *' # Автоматический запуск каждые 3 часа

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run script
      run: python update_leaderboard.py

    - name: Commit and Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "📊 Авто-обновление лидерборда плей-офф"
        file_pattern: "README.md"
