name: Update Playoff Leaderboard

on:
  schedule:
    - cron: '0 9,21 * * *'
  workflow_dispatch: # Позволяет запускать обновление вручную кнопкой на GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread google-auth

    - name: Run script
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_PRIVATE_KEY_ID: ${{ secrets.GCP_PRIVATE_KEY_ID }}
        GCP_PRIVATE_KEY: ${{ secrets.GCP_PRIVATE_KEY }}
        GCP_CLIENT_EMAIL: ${{ secrets.GCP_CLIENT_EMAIL }}
      run: python update_leaderboard.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git diff-index --quiet HEAD || git commit -m "Авто-обновление лидерборда плей-офф"
        git push
